server.port=8081
spring.application.name=lab4Drivers
spring.datasource.url=jdbc:postgresql://drivers-db:5432/drivers_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=drivers_user
spring.datasource.password=drivers_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true


